######################################################################
# Automatically generated by qmake (3.1) Thu Mar 30 11:18:38 2017
######################################################################

TEMPLATE = app
TARGET = fizix
INCLUDEPATH += .
CONFIG += console

# Input
QT += core
QT += widgets
HEADERS += window.h commontypes.h renderarea.h shapeobj.h
SOURCES += window.cpp main.cpp renderarea.cpp shapeobj.cpp
